name: Test
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:  
  build:
    name: Test
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      consul:
        image: consul
        ports:
        - 8600:8600/udp
        - 8500:8500/tcp
        env:
          CONSUL_BIND_INTERFACE: eth0
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out code
        uses: actions/checkout@v2

      - name: Add dummy service to consul
        run: curl -X PUT -d '{"Name":"vault","Tags":["third","v3"],"Address":"172.17.0.3","Port":8200}' http://consul:8500/v1/agent/service/register

      - name: Test
        run: go test -v -count=1 ./...
